const CLUBS = [
  // ── COUNTY TEAMS ──────────────────────────────
  {g:"🏆 GAA County Teams", n:"Antrim", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Armagh", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Carlow", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Cavan", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Clare", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Cork", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Derry", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Donegal", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Down", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Dublin", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Fermanagh", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Galway", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Kerry", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Kildare", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Kilkenny", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Laois", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Leitrim", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Limerick", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Longford", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Louth", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Mayo", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Meath", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Monaghan", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Offaly", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Roscommon", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Sligo", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Tipperary", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Tyrone", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Waterford", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Westmeath", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Wexford", badge:"GAA"},
  {g:"🏆 GAA County Teams", n:"Wicklow", badge:"GAA"},

  // ── LGFA COUNTY TEAMS ──────────────────────────
  {g:"🏆 LGFA County Teams", n:"Antrim Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Armagh Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Carlow Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Cavan Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Clare Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Cork Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Derry Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Donegal Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Down Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Dublin Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Fermanagh Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Galway Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Kerry Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Kildare Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Laois Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Leitrim Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Limerick Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Longford Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Louth Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Mayo Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Meath Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Monaghan Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Offaly Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Roscommon Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Sligo Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Tipperary Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Tyrone Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Waterford Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Westmeath Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Wexford Ladies", badge:"LGFA"},
  {g:"🏆 LGFA County Teams", n:"Wicklow Ladies", badge:"LGFA"},

  // ── CONNACHT ──────────────────────────────────
  {g:"🟢 Connacht — Galway", n:"Annaghdown", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Athenry", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Ballinasloe", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Beagh", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Caltra", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Claregalway", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Corofin", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Cortoon Shamrocks", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Dunmore MacHales", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Galway Commercials", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Kilconieron", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Milltown", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Monivea-Abbey", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Mountbellew-Moylough", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Moycullen", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Oranmore-Maree", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Salthill-Knocknacarra", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"St Brendan's", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Tuam Stars", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Tubbercurry", badge:"GAA"},
  {g:"🟢 Connacht — Galway", n:"Annaghdown", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Ahascragh-Caltra Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Corofin Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Kilkerrin-Clonberne", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Milltown Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Moycullen Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Oughterard Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Salthill-Knocknacarra Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"St James Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Galway", n:"Tuam Stars Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Aghamore", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ardnaree Sarsfields", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Balla", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ballaghaderreen", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ballina Stephenites", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ballinrobe", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ballintubber", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Ballycastle", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Belmullet", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Castlebar Mitchels", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Charlestown Sarsfields", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Claremorris", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Crossmolina Deel Rovers", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Davitts", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Hollymount-Carramore", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Kilmaine", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Knockmore", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Louisburgh", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Parke-Keelogues-Crimlin", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Swinford", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Westport", badge:"GAA"},
  {g:"🟢 Connacht — Mayo", n:"Aghamore Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Carnacon", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Castlebar Mitchels Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Charlestown Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Claremorris Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Knockmore Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Moy Davitts", badge:"LGFA"},
  {g:"🟢 Connacht — Mayo", n:"Reape Tourlestrane", badge:"LGFA"},
  {g:"🟢 Connacht — Roscommon", n:"Boyle", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Clann na nGael", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Elphin", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Fuerty", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Michael Glaveys", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Roscommon Gaels", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"St Brigid's", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"St Faithleach's", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Strokestown", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Tulsk", badge:"GAA"},
  {g:"🟢 Connacht — Roscommon", n:"Clann na nGael Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Roscommon", n:"Kilbride Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Sligo", n:"Curry", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Drumcliffe-Rosses Point", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Easkey", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Enniscrone-Kilglass", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Geevagh", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Markievicz", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Naomh Éanna", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"St Mary's Sligo", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Tourlestrane", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Tubbercurry-Cloonacool", badge:"GAA"},
  {g:"🟢 Connacht — Sligo", n:"Curry Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Sligo", n:"Tourlestrane Ladies", badge:"LGFA"},
  {g:"🟢 Connacht — Leitrim", n:"Allen Gaels", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Ballinamore Sean O'Heslins", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Carrigallen", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Drumreilly", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Fenagh St Caillins", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Glencar-Manorhamilton", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Kiltubrid", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Leitrim Gaels", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"Mohill", badge:"GAA"},
  {g:"🟢 Connacht — Leitrim", n:"St Mary's Kiltoghert", badge:"GAA"},

  // ── MUNSTER ───────────────────────────────────
  {g:"🔴 Munster — Kerry", n:"Austin Stacks", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Ballydonoghue", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Castleisland Desmonds", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Dingle", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Dr Crokes", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"East Kerry", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Feale Rangers", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Gneeveguilla", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Kenmare District", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Killarney Legion", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Kilcummin", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Lispole", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Mid Kerry", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Milltown-Castlemaine", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Na Gaeil", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Rathmore", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"South Kerry", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"St Brendan's Killarney", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Templenoe", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Tralee Parnells", badge:"GAA"},
  {g:"🔴 Munster — Kerry", n:"Beaufort Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Castleisland Desmonds Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Dr Crokes Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Finuge Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Killarney Legion Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Knocknagoshel Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Na Gaeil Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Rathmore Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"St Brendan's Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Kerry", n:"Templenoe Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Ballincollig", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Carbery Rangers", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Castlehaven", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Cill na Martra", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Clonakilty", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Clyda Rovers", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Duhallow", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Éire Óg", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Fermoy", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Kanturk", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Kilshannig", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Macroom", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Mallow", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Mitchelstown", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Nemo Rangers", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Newcestown", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"O'Donovan Rossa", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"St Finbarr's", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Tracton", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Valley Rovers", badge:"GAA"},
  {g:"🔴 Munster — Cork", n:"Bantry Blues Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Donoughmore Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Éire Óg Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Fermoy Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Inch Rovers", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Kinsale Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Mourneabbey", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Nemo Rangers Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"O'Donovan Rossa Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Cork", n:"Rockbán Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Tipperary", n:"Arravale Rovers", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Cahir", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Clonmel Commercials", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Éire Óg Annacarty", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Fethard", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Galtee Rovers-Bansha", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Loughmore-Castleiney", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Moyle Rovers", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Mullinahone", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Upperchurch-Drombane", badge:"GAA"},
  {g:"🔴 Munster — Tipperary", n:"Aherlow Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Tipperary", n:"Cahir Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Tipperary", n:"Clonmel Commercials Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Tipperary", n:"Fethard Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Tipperary", n:"Loughmore-Castleiney Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Clare", n:"Cooraclare", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Doonbeg", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Éire Óg Clare", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Ennistymon", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Kilmihil", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Kilrush Shamrocks", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Lissycasey", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Miltown-Malbay", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"St Breckan's", badge:"GAA"},
  {g:"🔴 Munster — Clare", n:"Kilmihil Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Clare", n:"Lissycasey Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Clare", n:"Miltown Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Limerick", n:"Adare", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Ballylanders", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Dromcollogher-Broadford", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Fr Casey's", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Galbally", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Kilteely-Dromkeen", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Na Piarsaigh", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Newcastle West", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"St Kieran's", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Tournafulla", badge:"GAA"},
  {g:"🔴 Munster — Limerick", n:"Ballylanders Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Limerick", n:"Galbally Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Limerick", n:"Newcastle West Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Waterford", n:"Dungarvan", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"Kilrossanty", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"Rathgormack", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"St Saviour's", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"Stradbally", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"Tramore", badge:"GAA"},
  {g:"🔴 Munster — Waterford", n:"Kilrossanty Ladies", badge:"LGFA"},
  {g:"🔴 Munster — Waterford", n:"Rathgormack Ladies", badge:"LGFA"},

  // ── LEINSTER ──────────────────────────────────
  {g:"🔵 Leinster — Dublin", n:"Ballyboden St Enda's", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Castleknock", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Clontarf", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Crumlin", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Erin's Isle", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Fingallians", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Lucan Sarsfields", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Na Fianna", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Naomh Barróg", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Naomh Fionnbarra", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"O'Tooles", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Parnells", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Raheny", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Round Towers Clondalkin", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Brigid's Dublin", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Jude's", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Maur's Rush", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Oliver Plunkett-Eoghan Ruadh", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Peregrine's", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"St Sylvester's", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Templeogue Synge Street", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Thomas Davis", badge:"GAA"},
  {g:"🔵 Leinster — Dublin", n:"Ballyboden St Enda's Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"Clontarf Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"Foxrock-Cabinteely", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"Kilmacud Crokes Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"Na Fianna Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"Parnells Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"St Brigid's Ladies Dublin", badge:"LGFA"},
  {g:"🔵 Leinster — Dublin", n:"St Sylvester's Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Meath", n:"Donaghmore-Ashbourne", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Dunboyne", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Gaeil Colmcille", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Kilmainhamwood", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Monaghans", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Navan O'Mahonys", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Ratoath", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"St Colmcille's", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"St Patrick's Trim", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Summerhill", badge:"GAA"},
  {g:"🔵 Leinster — Meath", n:"Donaghmore-Ashbourne Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Meath", n:"Dunboyne Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Meath", n:"Nobber Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Meath", n:"Ratoath Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Meath", n:"St Peter's Ladies Dunboyne", badge:"LGFA"},
  {g:"🔵 Leinster — Kildare", n:"Athy", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Celbridge", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Clane", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Confey", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Eadestown", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Leixlip Nationalists", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Maynooth", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Moorefield", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Naas", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Sarsfields Newbridge", badge:"GAA"},
  {g:"🔵 Leinster — Kildare", n:"Athy Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Kildare", n:"Moorefield Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Kildare", n:"Sarsfields Ladies Kildare", badge:"LGFA"},
  {g:"🔵 Leinster — Laois", n:"Arles-Kilcruise", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Arles-Killeen", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Ballylinan", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Graiguecullen", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Killeshin", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Laois Gaels", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Mountmellick Gaels", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Portarlington", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Portlaoise", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"St Joseph's Laois", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Sarsfields Laois", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"The Heath", badge:"GAA"},
  {g:"🔵 Leinster — Laois", n:"Ballylinan Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Laois", n:"Killeshin Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Laois", n:"Portarlington Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Laois", n:"Sarsfields Ladies Laois", badge:"LGFA"},
  {g:"🔵 Leinster — Laois", n:"Timahoe Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Louth", n:"Ardee St Mary's", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"Cooley Kickhams", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"Dundalk Young Irelands", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"Glen Emmets", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"Naomh Máirtín", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"St Brides", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"St Joseph's Louth", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"St Mochta's", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"St Patrick's Lordship", badge:"GAA"},
  {g:"🔵 Leinster — Louth", n:"Naomh Máirtín Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Louth", n:"St Brigid's Knockbridge", badge:"LGFA"},
  {g:"🔵 Leinster — Westmeath", n:"Athlone", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Coralstown-Kinnegad", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Garrycastle", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Killucan", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Lough Ree Rovers", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Mullingar Shamrocks", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Rosemount", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"St Loman's Mullingar", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Tyrrellspass", badge:"GAA"},
  {g:"🔵 Leinster — Westmeath", n:"Athlone Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Westmeath", n:"Garrycastle Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Westmeath", n:"St Loman's Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Offaly", n:"Cappincur", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Clara", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Edenderry", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Ferbane", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Gracefield", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Rhode", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"St Brigid's Offaly", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"St Rynagh's", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Tullamore", badge:"GAA"},
  {g:"🔵 Leinster — Offaly", n:"Clara Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Offaly", n:"Rhode Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Offaly", n:"St Brigid's Ladies Offaly", badge:"LGFA"},
  {g:"🔵 Leinster — Wexford", n:"Buffers Alley", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Clongeen", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Ferns St Aidan's", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Kilanerin", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Naomh Éanna Wexford", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Oulart-The Ballagh", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"St Anne's", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"St James's Ramsgrange", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Wexford Gaels", badge:"GAA"},
  {g:"🔵 Leinster — Wexford", n:"Glynn-Barntown Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Wexford", n:"St Anne's Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Wicklow", n:"Arklow Geraldines", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Baltinglass", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Blessington", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Carnew Emmets", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Éire Óg Greystones", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Kilcoole", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Rathnew", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"St Patrick's Wicklow", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Tinahely", badge:"GAA"},
  {g:"🔵 Leinster — Wicklow", n:"Baltinglass Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Wicklow", n:"Carnew Emmets Ladies", badge:"LGFA"},
  {g:"🔵 Leinster — Carlow", n:"Éire Óg Carlow", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"Kilbride", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"Muinebheag", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"Old Leighlin", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"Palatine", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"St Mullins", badge:"GAA"},
  {g:"🔵 Leinster — Carlow", n:"Éire Óg Ladies Carlow", badge:"LGFA"},
  {g:"🔵 Leinster — Longford", n:"Abbeylara", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Ballymahon", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Carrickedmond", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Clonguish", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Dromard", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Killoe Emmet Óg", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Longford Slashers", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"Mostrim", badge:"GAA"},
  {g:"🔵 Leinster — Longford", n:"St Brigid's Ladies Longford", badge:"LGFA"},

  // ── ULSTER ────────────────────────────────────
  {g:"🟡 Ulster — Tyrone", n:"Ardboe", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Carrickmore", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Clonoe O'Rahillys", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Cookstown Fr Rocks", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Coalisland Fianna", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Dungannon Thomas Clarke", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Errigal Ciaran", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Killyclogher", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Killeeshil", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Moortown St Malachy's", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Omagh St Enda's", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Pomeroy Plunketts", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Strabane", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Trillick St Macartan's", badge:"GAA"},
  {g:"🟡 Ulster — Tyrone", n:"Beragh Red Knights Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Tyrone", n:"Carrickmore Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Tyrone", n:"Clann na nGael Ladies Tyrone", badge:"LGFA"},
  {g:"🟡 Ulster — Tyrone", n:"Errigal Ciaran Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Tyrone", n:"Galbally Pearses Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Armagh", n:"Ballymacnab", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Belleeks", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Clann Eireann", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Crossmaglen Rangers", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Dromintee", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Granemore", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Keady Mochtas", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Killeavy", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Maghery Sean McDermotts", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Mullaghbawn", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Silverbridge Harps", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Sarsfields Armagh", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"St Peter's Lurgan", badge:"GAA"},
  {g:"🟡 Ulster — Armagh", n:"Clann Eireann Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Armagh", n:"Clann na nGael Ladies Armagh", badge:"LGFA"},
  {g:"🟡 Ulster — Armagh", n:"Crossmaglen Rangers Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Armagh", n:"Granemore Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Armagh", n:"Killeavy Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Derry", n:"Ballinascreen", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Bellaghy", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Coleraine", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Derry City", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Dungiven Celtic", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Éire Óg Limavady", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Glen", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Kilrea", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Lavey", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Magherafelt", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Newbridge", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Slaughtneil", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Swatragh", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Upperlands", badge:"GAA"},
  {g:"🟡 Ulster — Derry", n:"Ballinascreen Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Derry", n:"Lavey Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Derry", n:"Slaughtneil Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Donegal", n:"Aodh Ruadh", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Ardara", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Bundoran", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Cloughaneely", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Glenswilly", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Gweedore", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Kilcar", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Killybegs", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Letterkenny Gaels", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"MacCumhaills", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Milford", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Naomh Conaill", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"St Eunan's", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"St Michael's", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Termon", badge:"GAA"},
  {g:"🟡 Ulster — Donegal", n:"Aodh Ruadh Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Donegal", n:"MacCumhaills Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Donegal", n:"Naomh Columba Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Donegal", n:"St Eunan's Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Donegal", n:"Termon Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Down", n:"An Riocht", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Annaclone", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Ardglass", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Atticall", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Ballyholland Harps", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Ballykinlar", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Ballymartin", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Bredagh", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Bright", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Bryansford", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Burren", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Carryduff", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Castlewellan", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Clann na Banna", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Clonduff", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Cumann Pheadair Naofa", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Darragh Cross", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Dromara", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Dromore", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Drumaness", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Drumgath", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Dundrum", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"East Belfast", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Glasdrumman", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Glenn", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"John Mitchels GFC", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Kilclief", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Kilcoo", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Liatroim Fontenoys", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Longstone", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Loughinisland", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Mayobridge", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Newry Bosco", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Newry Shamrocks", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"RGU Downpatrick", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Rostrevor", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Saul", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Saval", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"St John's Drumnaquoile", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"St Pauls", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Teconnaught", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Tullylish", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Warrenpoint", badge:"GAA"},
  {g:"🟡 Ulster — Down", n:"Clonduff Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Down", n:"Kilcoo Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Down", n:"Saval Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Antrim", n:"Aghagallon", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Ballycastle McQuillan's", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Cargin", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Creggan Kickhams", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Crosserlough", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Cushendall", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Dunloy", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Lámh Dhearg", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Naomh Éanna Antrim", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Portglenone", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Rasharkin", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"St Brigid's Antrim", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"St Enda's Glengormley", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"St Gall's", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"St Paul's Antrim", badge:"GAA"},
  {g:"🟡 Ulster — Antrim", n:"Cargin Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Antrim", n:"Lámh Dhearg Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Antrim", n:"St Brigid's Ladies Antrim", badge:"LGFA"},
  {g:"🟡 Ulster — Cavan", n:"Ballymachugh", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Bailieborough Shamrocks", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Breffni Gaels", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Butlersbridge", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Castlerahan", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Crosserlough Cavan", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Killygarry", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Kingscourt Stars", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Lacken", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Laragh United", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Munterconnaught", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Ramor United", badge:"GAA"},
  {g:"🟡 Ulster — Cavan", n:"Cavan Gaels Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Cavan", n:"Lacken Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Monaghan", n:"Castleblayney Faughs", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Clones", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Corduff", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Doohamlet", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Emyvale", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Inniskeen Grattans", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Latton O'Brien's", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Monaghan Harps", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Scotstown", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Truagh Gaels", badge:"GAA"},
  {g:"🟡 Ulster — Monaghan", n:"Emyvale Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Monaghan", n:"Inniskeen Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Monaghan", n:"Donaghmoyne Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Fermanagh", n:"Aghadrumsee", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Ballinamallard", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Derrygonnelly Harps", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Ederney St Joseph's", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Enniskillen Gaels", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Irvinestown", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Lisnaskea Emmets", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Newtownbutler", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Roslea Shamrocks", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Teemore Shamrocks", badge:"GAA"},
  {g:"🟡 Ulster — Fermanagh", n:"Derrygonnelly Ladies", badge:"LGFA"},
  {g:"🟡 Ulster — Fermanagh", n:"Enniskillen Gaels Ladies", badge:"LGFA"},
];
